#!/bin/sh

create()
{
	name=$1
	file="$HOME/.onemach/essay_remote"
	gitRemote=`head -n 1 $file`
	git clone $gitRemote $name
	cd $name
	git checkout -b $name master
	echo $name > .writing_branch
}

sync()
{
	name=$1
	cd $name
	git add *
	git commit -m "nothing"
	branch=`head -n 1 .writing_branch`
	git push origin $branch
}

if [ $1 = 'create' ]; then
	create $2
elif [ $1 = 'sync' ]; then
	sync $2
fi
